### ISSUE TITLE
Missing bonus points for "Hexenmeister"

### ISSUE THREAD

**Issue by Phameous** [benjamin-klamerek/fantasy-realm-scoring#13]
Unfortunately, I only have the German version of the game, so my description will relate to the card names in German language.
When having the building card "Verlies" (probably something like "dungeon" in english) the bonus for also having the magician "Hexenmeister" (might be "Warlock Lord") was not calculated. The other bonuses in this case (another building and a flood I believe) were summed up correctly.
Don't hesitate to ask for more specifics if you need any
Greetings and congratulations to a nice developed app!

**Comment by benjamin-klamerek** [comment]
Thank you for taking the time to post your feedback here.

I tried the combination of dungeon + warlock lock and the score is 37 and it seems correct (I have a +5 bonus from the dungeon card)

Could you provide the exact card list that you're using with the score ?
I tried some other combinations but I was not able to find a bug with dungeon implementation. 

Best regards

**Comment by Phameous** [comment]
Hey there,

sorry to hear that you couldn't reproduce the situation. Sadly, I didn't take a picture of the different hands involved, so I am unable to reproduce it either.
For now, you can close the issue and I will get back to it, if I accidentally figure out how it came up ;)

All the best
