### ISSUE TITLE
Scan discard area

### ISSUE THREAD

**Issue by NicolaiRuckel** [benjamin-klamerek/fantasy-realm-scoring#14]
For all the Undead cards that count cards in the discard area, it would be nice if it was possible to scan that, too.

**Comment by benjamin-klamerek** [comment]
Hi Nicolai, thank you for your feedback.

But for me you can already do that. There is a dedicated "Discard area" button next to "Add player".
On that screen you have the "Scan" option to detect cards from the discard area.

Example : if a player has the "Dark queen" card and discard area contains 5 Lands, a bonus of +25 is effective.

Maybe "Discard area" is not well translated. Which language do you use ?
I'm currently working on replacing this button by a dedicated element in player list. I hope it will be more clear.
(I admit I'm still looking fo rthe best way to display that part)

Best regards

**Comment by NicolaiRuckel** [comment]
Yes, the translation confused me. It's "Bereich verwerfen" which means "clean up" so I expected it to clear the player list. If I remember correctly, the discard area is called "Ablagebereich" in German. I'll double-check later and when I have some time, I can open a pull request with different translations.

**Comment by benjamin-klamerek** [comment]
As I though. 
I'm using google translate for common buttons and labels. I, of course, don't have the game in all languages (only french).

If you can confirm the exact name used in the rules, I will update it directly in my current dev branch. 
I plan to release a new version today.

**Comment by NicolaiRuckel** [comment]
I just checked and opened #15 for that.

**Comment by benjamin-klamerek** [comment]
Thank you very much for you contribution.
I still have few tests to perform and I will release it.
