### ISSUE TITLE
Wrong score in Weather scenario

### ISSUE THREAD

**Issue by 22dasi1bwi** [benjamin-klamerek/fantasy-realm-scoring#21]
Hey there,

I read the [official documentation](https://wizkids.com/posters/repository/wizkids/FR_Rulebook-WEB.pdf). They describe a scenario in the Q&A section where the following Cards are in the hand:
* _Wildfire_
* _Blizzard_
* _Great Flood_

According to the documentation the remaining active (not blanked) cards are: _Blizzard_ and _Wildfire_, resulting in a total score of 65 (_Blizzard_=30 - 5 (from _Wildfire_), _Wildfire_=40).
The app however shows that both _Great Flood_ **and** _Wildfire_ are blanked, resulting in a total score of 30. 

The last update from the App I'm using is from 06.01.2022.

Thanks for looking into this!

Cheers :smile:

**Comment by benjamin-klamerek** [comment]
Hello,

Yes, you're right. There is a bug about ordering. 
By checking the FAQ, I also found another bug about basilik rule.

I will add unit tests and fix these cases.

Thanks

**Comment by 22dasi1bwi** [comment]
Glad to hear that :smile: . Sounds good :+1:

**Comment by benjamin-klamerek** [comment]
The version 0.19 is released.

This bug should be fixed. (It's working on my phone :-))

**Comment by 22dasi1bwi** [comment]
Nice! I can confirm that it is working. Good job :+1:
