### ISSUE TITLE
German Translation + Jester

### ISSUE THREAD

**Issue by ncZabien** [benjamin-klamerek/fantasy-realm-scoring#4]
Hi, I really like the work you are did and wanted to help at least a little, although I'm not really familiar with GitHub (yet).
Below I've added the translated file for the german version and I already have included a translation for the Jester promo card, which seems to be not in there yet.
I hope this helps. 
Also, GitHub won't allow me to upload a .xml file directly, so a .zip must do for now.

[strings.zip](https://github.com/benjamin-klamerek/fantasy-realm-scoring/files/7229588/strings.zip)

**Comment by benjamin-klamerek** [comment]
Hi,

Thank you very much for your work. I will take a look at it and integrate
that in the next version.
For the jester promo card, I don't know if I will add it in the next
version (maybe the one after).
I have to check if the card was translated in other languages (the text
recognition works with the title name).

Best regards,

Benjamin Klamerek

**Comment by benjamin-klamerek** [comment]
Will be in next release (v0.6)
