### ISSUE TITLE
Evaluation of collector

### ISSUE THREAD

**Issue by alanjenningsohio** [benjamin-klamerek/fantasy-realm-scoring#40]
Sorry for not digging or doing a good check on this, so delete this if covered. 
It seems the evaluation of the collector is prior to all effects, or doesn't account for book of changes or mirage. 
Island (clearing wildfire) 
Great flood
Fountain
Wildfire
Book of changes (making wildfire a flood) 
Mirage (choosing great flood) 
Collector (bonus of 40, showing only 4 floods) 
Hmmm... Or maybe it's from the mirage selecting a card already present? 
Thanks!

**Comment by benjamin-klamerek** [comment]
Hello,

The application is right. The collector counts "different" cards.
With mirage, you duplicate "great flood" so you have 2 times the same card.

If instead, you select another card like the "Swamp" with Mirage then Collector will count 5 cards.

**Comment by alanjenningsohio** [comment]
Ah, I read that as separable, meaning physically distinct; not by name. 
Thanks for the second set of eyes!
