### ISSUE TITLE
Add Ukrainian localisation 

### ISSUE THREAD

**Issue by modnoise** [benjamin-klamerek/fantasy-realm-scoring#42]
Hi, I would like to add Ukrainian language to the app.

**Comment by modnoise** [comment]
I will add the appropriate xml file in the near future. Hope my enhancement will be implemented operatively. This is a huge support to Ukrainian board game localizations

**Comment by modnoise** [comment]
You mean the "Scan" functionality? I do not mind if this one will not be implemented. That's fine. I just want this map to be localized with Ukrainian.
Here is the xml:

[ua.zip](https://github.com/benjamin-klamerek/fantasy-realm-scoring/files/10468211/ua.zip)

I did not translate all the effects of the cards into my language, because they are not displayed anywhere in the program. 
Also it would be nice, if you add the following label on the Setting page about the author of translating: "Перекладено українською мовою: @mod_noise. Слава Україні"

**Comment by modnoise** [comment]
Sorry, I forgot to add some other options, will post them in the next comment soon, could you add them to the xml file I sent? Thanks!

**Comment by modnoise** [comment]
- `<string name="language_label_ukrainian" translatable="false">українська</string>`: this is to be added to `app/src/main/res/values/strings.xml`
- My file to be added to `app/src/main/res/values-ua/strings.xml`
- And do not forget to add the following variable to `app/src/main/java/com/klamerek/fantasyrealms/util/LocaleManager.kt`
`val ukrainian = Language("UKRAINIAN_ID", R.string.language_label_ukrainian, "ua", "UA")`
- Also don't forget about the `languages` variable.

**Comment by benjamin-klamerek** [comment]
I saw your PR.

For contributions, I already have this : page https://github.com/benjamin-klamerek/fantasy-realm-scoring/wiki/Contributors please note that I can put your name but it will be neutral and in english.

Best regards

**Comment by benjamin-klamerek** [comment]
PR is merged (even if you have not reduced the 2 labels in settings screen).

It took me more time to build, I had to update gradle and some dependencies...

The package is done and pushed in my internal test env.
It should be available on my smartphone in few hours.
I will perform some manual testing to ensure that nothing big is broken, and, if it's the case, will release it for everybody else.

Best regards

**Comment by modnoise** [comment]
@benjamin-klamerek Thank you! I will also take a look at localization and fix some other issues in Settings

**Comment by modnoise** [comment]
@benjamin-klamerek pls review and merge PR

**Comment by benjamin-klamerek** [comment]
Merged
