### ISSUE TITLE
Add sorting by base power

### ISSUE THREAD

**Issue by modnoise** [benjamin-klamerek/fantasy-realm-scoring#46]
Feature request to add a button on the page with selecting cards that change sorting by card number/base power (from 0 (Joker cards at the top) to 40 (Fire card at the bottom of the list))

**Comment by benjamin-klamerek** [comment]
Hello,

I'm not convinced that this feature is really useful.
Cards are already grouped by family and you can display the "number" (like 5/42).

Moreover, I'm not sure about where you want to add this button. 
I'm not a UX/UI expert (you can guess it when you see the app :-) ) but on mobile, placing a button correctly is not easy.
